resolver: lts-11.11

packages:
- .
- location:
    git: https://github.com/runeksvendsen/orderbook.git
    commit: 2e2551e1333ec7bc1c4745e6a547bdf4887d79b4
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/crypto-venues.git
    commit: 84043b03ba0292d19477f1f765ac91e812edc056
  extra-dep: true


# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- logging-3.0.5
- rate-limit-1.4.0
- safe-money-0.6
### BEGIN safe-money deps
- serialise-0.2.0.0@sha256:377bc9a3f2be921496db65d6d1d9be6f8903c9d868a39dffd4831f5c61154964
- xmlbf-0.4.1@sha256:c0a7e38f611e4090e05debe22fee75e68aa97d59178b3098de3ca7751bf66709
- cborg-0.2.0.0@sha256:4cc743e688046e0262c0d2ddcc786a4ebdd8b1e949c2055b4aef7eae5483eb90
- half-0.2.2.3@sha256:52386a48e7fd42f4a1d49799073bb3d04477168c88b6541d5f66637d7c2e838c
### END safe-money deps
- time-units-1.0.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
